version: "3"

services:
  frontend:
    depends_on:
      - backend
      - db
    container_name: frontend
    hostname: frontend
    build: ./srcs/frontend
    image: frontend:${TAG}
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    networks:
      - docker-network

  backend:
    depends_on:
      db:
        condition: service_healthy
    container_name: backend
    hostname: backend
    build: ./srcs/backend
    image: backend:${TAG}
    ports:
      - "5000:5000"
      - "5555:5555" # for Prisma Studio
    restart: always
    env_file:
      - .env
    networks:
      - docker-network

  db:
    container_name: db
    hostname: postgres
    build: ./srcs/db
    image: db:${TAG}
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - DB:/var/lib/postgresql/data
    networks:
      - docker-network

volumes:
  DB:

networks:
  docker-network:
    driver: bridge
