# This is just a temp file to test the connection between PostgreSQL and NestJS

version: "3"

services:
  db:
    image: postgres:latest
    container_name: db
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=mydb
    env_file:
      - sample.env
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge